- capitalname: "ROOF REPAIR AND ROOF MAINTENANCE"
  icon: hammer
  title: Roof repair and roof maintenance
  permalink: /services/roof-repair
  more: More on roof repair & maintenance
  shortdes: TP Roofing are experts at sourcing and rectifying roof leaks. We prolong the life of your roof by providing roof maintenance services, fixing your leaking roof and delivering the best possible roofing solutions for your roofing needs...
  items: 
  - name: Replace broken or missing tiles or ridge caps
    permalink: /services/roof-repair-maintenance/replace-broken-missing-tiles-ridge-caps
    image: "/assets/images/services/"

  - name: Seal possum entry points
    permalink: /services/roof-repair-maintenance/seal-possum-entry-points
    image: "/assets/images/services/"

  - name: Install roof ventilation whirlybirds
    permalink: /services/roof-repair-maintenance/install-roof-ventilation
    image: "/assets/images/services/"

  - name: Install leaf screen
    permalink: /services/roof-repair-maintenance/install-leaf-screen
    image: "/assets/images/services/"

  - name: Clean gutters and down pipes of debris
    permalink: /services/roof-repair-maintenance/clean-gutters-and-down-pipes-of-debris
    image: "/assets/images/services/"

  - name: Source and repair roof leaks
    permalink: /services/roof-repair-maintenance/source-and-repair-roof-leaks
    image: "/assets/images/services/"

  - name: Repair storm damaged roof
    permalink: /services/roof-repair-maintenance/repair-storm-damaged-roof
    image: "/assets/images/services/"

  - name: Replace valleys, gutters and downpipes
    permalink: /services/roof-repair-maintenance/replace-valleys-gutters-and-downpipes
    image: "/assets/images/services/"

  - name: Re-bed and point ridge caps and gable tiles
    permalink: /services/roof-repair-maintenance/re-bed-and-point-ridge-caps-and-gable-tiles
    image: "/assets/images/services/"

  - name: Install roof flashings
    permalink: /services/roof-repair-maintenance/install-roof-flashings
    image: "/assets/images/services/"


- capitalname: "ROOF REPLACEMENT (RE-ROOFING)"
  icon: color-wand
  title: Roof replacement (re-roofing)
  permalink: /services/re-roofing-roof-replacement
  more: More on roof replacement
  shortdes: TP Roofing will replace your roof with the minimum of inconvenience, we excel at liaising with our clients and running our crews efficiently delivering a finished product that enhances your home and protects your most valuable asset...

- capitalname: "NEW ROOF INSTALLATION"
  icon: build
  title: New roof installation
  permalink: /services/new-roof-installation
  more: More on new roof
  shortdes: TP Roofing installs new tiled roofs of any size or scope Sydney wide. Handpicked by Monier Roofing to join their elite team of Roofing specialists enables us to offer you Monier terracotta and concrete tiles at competitive prices...
    


